### ISSUE TITLE
how to store the results of Community.cluster

### ISSUE THREAD

**Issue by weikang9009** [spatialucr/geosnap#145]
Currently, the [`Community`](https://github.com/spatialucr/geosnap/blob/master/geosnap/data/data.py#L767) class has a method [`cluster`](https://github.com/spatialucr/geosnap/blob/master/geosnap/data/data.py#L884) which conducts neighborhood segmentation (clustering) on selected census variables.

The results of the neighborhood cluster labels is appended to a copy of the  **original** geopandas dataframe as an additional column. Then, a new instance of `Community` is created using this dataframe and returned to the user. 

Two issues with this strategy:
* users won't be able to know which variables are used to construct the neighborhood segmentation since we are returning the full original data table.
* some tracts (rows) are abandoned because of the missing values in the selected variables and years, and this is hidden from users if we return the full data table.

**Comment by knaaptime** [comment]
this is a metadata problem, as i understand it, right? When a user creates a custer analysis from a community, they get back a new community with cluster labels attached, and the question is whether we need additional metadata handling?

> users won't be able to know which variables are used to construct the neighborhood segmentation since we are returning the full original data table.

is this kinda like using the dataframe columns as implicit metadata? so like, the user will know which variables were part of the cluster analysis because they are the only variables left on the dataframe of the new community? That would solve the problem but there are a few things i dont like about that approach. 

First, i dont like removing valuable data as a way of managing metadata. Sometimes you want to use the cluster labels to summarize *other* data you have for a community without including it in the cluster analysis (e.g. clustering on race and income, but then examining the median age in each of the resulting clusters to see if other patterns emerge). You could attach it with a join, but i'd argue that's a bigger hassle than just giving the user back what they put in. I'd rather remember which columns I used for the cluster than have to merge more variables back (but i could be in the minority...).

Second, when you call `cluster` it returns a new community, so an alternative way to handle this would be to just store communities with different cluster params in separate variables. Since you can return the cluster instance itself (which includes *all* the metadata about which variables were used, which `k`, etc) along with the new community, you could use that option to build a dict or something of like `{community: clusterer}` with different params with each associated set of cluster labels, which might be different way to solve this problem? 

Third, it seems conceptually very similar to the second problem that you raise, which is that once you've defined a community, it's reasonable to keep *all* the data about it intact, including which geoms are within its extent and which variables you have to describe it. I dont like the idea of dropping variables any more than i like the idea of dropping observations.

to that end, I agree this is not ideal:

> some tracts (rows) are abandoned because of the missing values in the selected variables and years, and this is hidden from users if we return the full data table.

ideally we should return all the tracts and just have NAs for cluster labels if the input data contain NAs... I could swear this is how it's currently implemented but i need to double check. I remember there being some problems with the spatial clusters.

so i think this is kinda a question of philosophy. Do we want to maintain the integrity of the community and keep all cases and variables? Or do we want to give primacy to the cluster analysis and remove variables and cases that dont apply to that particular cluster instance? I definitely vote for the former, understand arguments for the latter, and would welcome more input. I think we just need to keep consistency (i.e. keep rows **and** columns or drop both).

**Comment by weikang9009** [comment]
`so i think this is kinda a question of philosophy. Do we want to maintain the integrity of the community and keep all cases and variables? Or do we want to give primacy to the cluster analysis and remove variables and cases that dont apply to that particular cluster instance? I definitely vote for the former, understand arguments for the latter, and would welcome more input. I think we just need to keep consistency (i.e. keep rows and columns or drop both).`

I would vote for the second strategy. It is important that we reveal the computation process to the users:
* what observations are dropped/kept because of NAs 
* what columns (variables) (and also rows if not all available census years are selected) are selected and thus responsible for the clustering output

Users already have the original full data - it appears redundant to me that we return the original table to them.

Either way, helper functions for further data transformation will be useful: for long-to-wide transformation, wide-to-long transformation, merge, etc. These functions/methods should be specific to the `Community` class and will have more meaningful names than the pandas "counterparts".

**Comment by knaaptime** [comment]
> what observations are dropped/kept because of NAs

if we adopt the first strategy, you know which variables were dropped because they dont have a cluster label

> what columns (variables) (and also rows if not all available census years are selected) are selected and thus responsible for the clustering output

the user **knows** which columns are part of the cluster analysis because they just chose them in the last call to `cluster`. It's the user's responsibility to know to know their dataset and which variables are available in each year

> Users already have the original full data - it appears redundant to me that we return the original table to them.

it's very likely you want to do analysis with other variables beyond those used in the cluster analysis, so it's not redundant to include them it's a hassle to remove them because then the user has to go through the trouble of adding them back. Otherwise, why wouldnt you just use scikit-learn or another cluster provider directly?

> Either way, helper functions for further data transformation will be useful: for long-to-wide transformation, wide-to-long transformation, merge, etc. These functions/methods should be specific to the Community class and will have more meaningful names than the pandas "counterparts".

definitely agree, though we'll need to think this through carefully, since a `Community` is a long-form dataset by definition

**Comment by knaaptime** [comment]
resolved by #158
