### ISSUE TITLE
remove property decorators from datasets

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/geosnap#169]
for sake of API consistency and better sphinx docs, all the datasets should be implemented as methods, rather than a mix of methods and properties

**Comment by weikang9009** [comment]
Agreed. Properties will be identified as attributes and rendered as [autoattribute](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autoattribute) which will print out values of the attributes rather than displaying the docstrings describing and explaining the attributes/properties. 

A current example is `geosnap.datasets.ncdb`
![image](https://user-images.githubusercontent.com/7359284/69284873-7abd7480-0ba4-11ea-98bc-c3d29043cf51.png)

**Comment by knaaptime** [comment]
resolved by #179
