### ISSUE TITLE
mapclassify pooling on tsplot

### ISSUE THREAD

**Issue by AnGWar26** [spatialucr/geosnap#260]
Would be very useful to have `mapclassify` pooled classifiers on tsplot. 

However, this seems to be on hold, as our plotting solution for `tsplot` has a bug where we can not retrieve the legend after it's created by the `geopandas` plotter. 

See: https://github.com/lukelbd/proplot/issues/224

**Comment by knaaptime** [comment]
@AnGWar26 take a look at #265 which allows for pooled classification in the (renamed) `plot_timeseries`. I think that should resolve this issue, but it doesnt touch the legend at all, so not sure about the proplot issues you're running into

one thing that would be nice to improve on #265 would be to plot a single legend (maybe off to the side) rather than repeating the same one below for each ax

**Comment by AnGWar26** [comment]
@knaaptime This seems like a great workaround for the problem that I was having! I'm glad to learn about the `classification_kwds` parameter in  the `geopandas` plotter, it seems like it's pretty useful.

**Comment by knaaptime** [comment]
agreed... i also didnt know about [`missing_kwds`](https://geopandas.org/mapping.html#missing-data) which is a nice recent addition. Do you want to keep this issue open while you work on the proplot legend? or should we close with #265 merged?

**Comment by AnGWar26** [comment]
It seems like it would be a good idea to close this issue, as it seems to be solved to me, unless you'd like to move to a different solution for this in the future? I think the improvement you mentioned for #265 where we use a single legend shouldn't be too difficult.

**Comment by knaaptime** [comment]
ok lets open a separate issue for that
